pipeline {
    agent any tools {
        maven 'Maven'
        jdk 'java17'
        git 'git'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/MariamLaghfiri/JaafRecruit/tree/main/JaafRecruit'
            }
        }

        stage('Build') {
            steps {
                script {

                    def microservices=['config-server','discovery','geteway','user','skills','education','Experience','job-seeker','job-posting','company','application']
                    microservices.each {
                        service ->dir(service) {
                            if (isUnix()) {
                                sh 'mvn clean install'
                            }

                            else {
                                bat 'mvn clean install'
                            }
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/chaimyaham/Chic-Choice-backend.git'

                // Run Maven on a Unix agent.
                bat "mvn test"
            }
        }

        post {
            success {
                echo 'Build succeeded!'
            }

            failure {
                echo 'Build failed!'
            }

            unstable {
                echo 'Build unstable!'
            }
        }
    }